language: cpp
compiler:
  - gcc
  - clang
# ...great programmers steal...
# Stolen from the .travis.yml used by rippled.
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-software-properties
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
  # # # - sudo apt-get install -qq libboost1.55-all-dev 
  # We want debug symbols for boost as we install gdb later
  # # # - sudo apt-get install -qq libboost1.55-dbg
  # # # - sudo apt-get install -qq mlocate
  # # # - sudo updatedb
  # # # - sudo locate libboost | grep /lib | grep -e ".a$"
  # # # - sudo apt-get install -qq protobuf-compiler libprotobuf-dev libssl-dev exuberant-ctags
  # We need gcc >= 4.8 for some c++11 features
  - sudo apt-get install -qq gcc-4.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 40 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8
  - sudo update-alternatives --set gcc /usr/bin/gcc-4.8
  # Stuff is gold. Nuff said ;)
  - sudo apt-get -y install binutils-gold
  # We can get a backtrace if the guy crashes
  - sudo apt-get -y install gdb
  # What versions are we ACTUALLY running?
  - g++ -v
  - clang -v

# Change this to your needs
script: make -C CodingChallenge
